version: "3.4"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpw
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./db/data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      # - ./docker-healthcheck.sh:/
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u rootuser -p rootpw --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
      # mongo:
      #   condition: service_healthy
# networks:
#   next-mongo-network:
#     driver: bridge
